// client/src/components/MainMenu.tsx
import { TribeType } from "webgl-test-shared/dist/tribes";
import { useCallback, useRef } from "react";
import { setGameState } from "./App";
import { createAudioContext } from "../sound";

const MAX_USERNAME_CHARS = 21;

/** Checks whether a given username is valid or not */
const usernameIsValid = (username: string): [warning: string, isValid: false] | [warning: null, isValid: true] => {
   if (username.length > MAX_USERNAME_CHARS) return ["Name cannot be more than " + MAX_USERNAME_CHARS + " characters long!", false];
   if (username.length === 0) return ["Name cannot be empty!", false];

   return [null, true];
}

interface MainMenuProps {
   readonly existingUsername: string | null;
   passUsername: (username: string) => void;
   passTribeType: (tribeType: TribeType) => void;
}
const MainMenu = ({ existingUsername, passUsername, passTribeType }: MainMenuProps) => {
   const nameInputBoxRef = useRef<HTMLInputElement | null>(null);
   const plainspeopleInputRef = useRef<HTMLInputElement | null>(null);
   const barbariansInputRef = useRef<HTMLInputElement | null>(null);
   const frostlingsInputRef = useRef<HTMLInputElement | null>(null);
   const goblinsInputRef = useRef<HTMLInputElement | null>(null);
   
   const getSelectedTribeType = (): TribeType => {
      if (plainspeopleInputRef.current !== null && plainspeopleInputRef.current.checked) {
         return TribeType.plainspeople;
      } else if (barbariansInputRef.current !== null && barbariansInputRef.current.checked) {
         return TribeType.barbarians;
      } else if (frostlingsInputRef.current !== null && frostlingsInputRef.current.checked) {
         return TribeType.frostlings;
      } else if (goblinsInputRef.current !== null && goblinsInputRef.current.checked) {
         return TribeType.goblins;
      }
      throw new Error("Not selected");
   }

   const getUsername = (): string => {
      // Get the inputted name
      const nameInputBox = nameInputBoxRef.current!;
      const inputUsername = nameInputBox.value;

      // If valid, set it as the username
      const [warning, isValid] = usernameIsValid(inputUsername);
      if (isValid) {
         return inputUsername;
      }

      alert(warning);
      return "";
   }

   // Handles username input
   const enterName = useCallback((): void => {
      const username = getUsername();
      if (username === "") {
         return;
      }

      const tribeType = getSelectedTribeType();

      createAudioContext();
      passUsername(username!);
      passTribeType(tribeType);
      setGameState("loading");
   }, [passUsername, passTribeType]);

   // When the name is entered
   const pressEnter = (e: KeyboardEvent): void => {
      if (e.code === "Enter") {
         enterName();
         e.preventDefault();
      }
   }

   return <div id="main-menu">
      <div className="content">
         <input ref={nameInputBoxRef} name="name-input" onKeyDown={e => pressEnter(e.nativeEvent)} type="text" placeholder="Enter name here" autoFocus />
         <form>
            <input ref={plainspeopleInputRef} type="radio" id="tribe-selection-plainspeople" name="tribe-selection" defaultChecked />
            <label htmlFor="tribe-selection-plainspeople">Plainspeople</label>
            <input ref={barbariansInputRef} type="radio" id="tribe-selection-barbarians" name="tribe-selection" />
            <label htmlFor="tribe-selection-barbarians">Barbarians</label>
            <input ref={frostlingsInputRef} type="radio" id="tribe-selection-frostlings" name="tribe-selection" />
            <label htmlFor="tribe-selection-frostlings">Frostlings</label>
            <input ref={goblinsInputRef} type="radio" id="tribe-selection-goblins" name="tribe-selection"/>
            <label htmlFor="tribe-selection-goblins">Goblins</label>
         </form>
         <button onClick={enterName}>Play</button>
      </div>
   </div>;
}

export default MainMenu;

// client/src/ui/MainMenu.svelte
<script lang="ts">
   import { TribeType } from "webgl-test-shared";
   import { establishNetworkConnection } from "../game/client";
   import { appState, AppState } from "../ui-state/app-state.svelte";

   const MAX_USERNAME_CHARS = 48

   let username = $state("");
   let tribeType = $state(TribeType.plainspeople);
   let isSpectating = $state(false);

   /** Checks whether a given username is valid or not */
   const usernameIsValid = (): [warning: string, isValid: false] | [warning: null, isValid: true] => {
      if (username.length > MAX_USERNAME_CHARS) return ["Name cannot be more than " + MAX_USERNAME_CHARS + " characters long!", false];
      if (username.length === 0) return ["Name cannot be empty!", false];
      
      return [null, true];
   }

   function pressEnter(e: KeyboardEvent): void {
      if (e.code === "Enter") {
         handlePlay();
      }
   }

   function handlePlay() {
      // Make sure the username is valid
      const [warning, isValid] = usernameIsValid();
      if (!isValid) {
         alert(warning);
         return;
      }

      establishNetworkConnection(username, tribeType, isSpectating);
      // @CLEANUP: MOVE INSIDE establishNetworkConnection
      appState.setState(AppState.loading);
   }
</script>

<div id="main-menu">
   <div class="content">
      <!-- svelte-ignore a11y_autofocus -->
      <input type="text" bind:value={username} onkeydown={pressEnter} placeholder="Enter name here" autoFocus />

      <div>
         <label for="tribe-selection-plainspeople">
            <input type="radio" id="tribe-selection-plainspeople" name="tribe-selection" defaultChecked />
            Plainspeople
         </label>
         <label for="tribe-selection-barbarians">
            <input type="radio" id="tribe-selection-barbarians" name="tribe-selection" />
            Barbarians
         </label>
         <label for="tribe-selection-frostlings">
            <input type="radio" id="tribe-selection-frostlings" name="tribe-selection" />
            Frostlings
         </label>
         <label for="tribe-selection-goblins">
            <input type="radio" id="tribe-selection-goblins" name="tribe-selection"/>
            Goblins
         </label>
         <label for="tribe-selection-dwarves">
            <input type="radio" id="tribe-selection-dwarves" name="tribe-selection"/>
            Dwarves
         </label>
      </div>

      <label>
         <input type="checkbox" bind:checked={isSpectating} />
         Spectate
      </label>
      
      <button onclick={handlePlay}>Play</button>
   </div>
</div>

<style>
   #main-menu {
      position: absolute;
      top: 0;
      right: 0;
      bottom: 0;
      left: 0;
      display: flex;
      align-items: center;
      justify-content: center;
   }
   
   button {
      display: block;
      padding: 0 10px;
   }
</style>
