// client/src/ui/game/inventories/CookingInventory.svelte
<script lang="ts">
   import { EntityType } from "webgl-test-shared/src/entities";
   import { COOKING_INGREDIENT_ITEM_TYPES, FUEL_SOURCE_ITEM_TYPES } from "webgl-test-shared/src/items/cooking-info";
   import ItemSlot from "./ItemSlot.svelte";
   import { InventoryName, ItemType } from "webgl-test-shared/src/items/items";
   import { getEntityType } from "../../../game/world";
   import { CookingComponentArray } from "../../../game/entity-components/server-components/CookingComponent";
   import { getInventory, InventoryComponentArray } from "../../../game/entity-components/server-components/InventoryComponent";
   import MenuElem from "../menus/MenuElem.svelte";
    import { entityInteractionState } from "../../../ui-state/entity-interaction-state.svelte";

   // @Hack: "!"
   const cookingEntity = entityInteractionState.selectedEntity!;
   const cookingComponent = CookingComponentArray.getComponent(cookingEntity)!;
   const inventoryComponent = InventoryComponentArray.getComponent(cookingEntity)!;
   
   const fuelInventory = getInventory(inventoryComponent, InventoryName.fuelInventory)!;
   const ingredientInventory = getInventory(inventoryComponent, InventoryName.ingredientInventory)!;
   const outputInventory = getInventory(inventoryComponent, InventoryName.outputInventory)!;

   const heatingBarProgress = cookingComponent.heatingProgress !== -1 ? cookingComponent.heatingProgress : 0;

   const entityType = getEntityType(cookingEntity);
</script>

<MenuElem id="cooking-inventory" className={`heating-inventory inventory${entityType !== EntityType.campfire ? " with-fuel" : ""}`}>
   <ItemSlot validItemSpecifier={(COOKING_INGREDIENT_ITEM_TYPES as unknown as Array<ItemType>).includes} className="ingredient-inventory" entityID={cookingEntity} inventory={ingredientInventory} itemSlot={1} />
   {#if entityType !== EntityType.campfire}
      <ItemSlot validItemSpecifier={(FUEL_SOURCE_ITEM_TYPES as unknown as Array<ItemType>).includes} className="fuel-inventory" entityID={cookingEntity} inventory={fuelInventory} itemSlot={1} />
   {/if}
   <ItemSlot validItemSpecifier={() => false} className="output-inventory" entityID={cookingEntity} inventory={outputInventory} itemSlot={1} />

   <div class="heating-progress-bar">
      <!-- @Cleanup: Hardcoded -->
      <div class="heating-progress-bar-heat" style:width="{heatingBarProgress * 4.5 * 20}px"></div>
   </div>
</MenuElem>

// client/src/components/game/inventories/CookingInventory.tsx
import { EntityType } from "battletribes-shared/entities";
import { COOKING_INGREDIENT_ITEM_TYPES, FUEL_SOURCE_ITEM_TYPES } from "battletribes-shared/items/cooking-info";
import ItemSlot from "./ItemSlot";
import { getSelectedEntity } from "../../../entity-selection";
import { InventoryName, ItemType } from "battletribes-shared/items/items";
import { getEntityType } from "../../../world";
import { CookingComponentArray } from "../../../entity-components/CookingComponent";
import { InventoryComponentArray } from "../../../entity-components/InventoryComponent";

const CookingInventory = () => {
   const cookingEntity = getSelectedEntity();
   const cookingComponent = CookingComponentArray.getComponent(cookingEntity);
   const inventoryComponent = InventoryComponentArray.getComponent(cookingEntity);

   const fuelInventory = inventoryComponent.getInventory(InventoryName.fuelInventory)!;
   const ingredientInventory = inventoryComponent.getInventory(InventoryName.ingredientInventory)!;
   const outputInventory = inventoryComponent.getInventory(InventoryName.outputInventory)!;

   const heatingBarProgress = cookingComponent.heatingProgress !== -1 ? cookingComponent.heatingProgress : 0;

   const entityType = getEntityType(cookingEntity);
   return <div id="cooking-inventory" className={`heating-inventory inventory${entityType !== EntityType.campfire ? " with-fuel" : ""}`}>
      <ItemSlot validItemSpecifier={(COOKING_INGREDIENT_ITEM_TYPES as unknown as Array<ItemType>).includes} className="ingredient-inventory" entityID={cookingEntity} inventory={ingredientInventory} itemSlot={1} />
      {entityType !== EntityType.campfire ? (
         <ItemSlot validItemSpecifier={(FUEL_SOURCE_ITEM_TYPES as unknown as Array<ItemType>).includes} className="fuel-inventory" entityID={cookingEntity} inventory={fuelInventory} itemSlot={1} />
      ) : undefined}
      <ItemSlot validItemSpecifier={() => false} className="output-inventory" entityID={cookingEntity} inventory={outputInventory} itemSlot={1} />

      <div className="heating-progress-bar">
         {/* @Cleanup: Hardcoded */}
         <div className="heating-progress-bar-heat" style={{width: heatingBarProgress * 4.5 * 20 + "px"}}></div>
      </div>
   </div>;
}

export default CookingInventory;
