// client/src/components/game/DeathScreen.tsx
import { randItem } from "webgl-test-shared/dist/utils";
import { useEffect, useState } from "react";
import Client from "../../client/Client";
import Game from "../../Game";
import { resetUsername, setGameState, setLoadingScreenInitialStatus } from "../App";
import { sendRespawnPacket } from "../../client/packet-creation";

const DEATH_TIPS: ReadonlyArray<string> = [
   "Always make sure your monitor is on, as otherwise it will not be on.",
   "Cyberbullying is a quick and effective way to get back at people after losing.",
   "Have you tried not dying?"
];

const quitGame = (): void => {
   resetUsername();
   setLoadingScreenInitialStatus("establishing_connection");
   setGameState("main_menu");
   Game.stop();
   Client.disconnect();
}

const DeathScreen = () => {
   const [tip, setTip] = useState<string>("");

   const randomiseTip = (): void => {
      const newTip = randItem(DEATH_TIPS);
      setTip(newTip);
   }

   useEffect(() => {
      randomiseTip();
   }, []);
   
   return <div id="death-screen">
      <div className="content">
         <h1 className="title">YOU DIED</h1>

         <p className="tip">Tip: {tip}</p>

         <div className="button-container">
            <button onClick={sendRespawnPacket}>Respawn</button>
            <button onClick={quitGame}>Quit</button>
         </div>
      </div>

      <div className="bg"></div>
   </div>;
}

export default DeathScreen;

// client/src/ui/game/DeathScreen.svelte
<script lang="ts">
   import { randItem } from "webgl-test-shared/src/utils";
   import { sendRespawnPacket } from "../../game/networking/packet-sending";
   import { quitGame } from "../../game/client";

   const RESPAWN_TIME_SECONDS = 8;

   const DEATH_TIPS: ReadonlyArray<string> = [
      "Always make sure your monitor is on, as otherwise it will not be on.",
      "Cyberbullying is a quick and effective way to get back at people after losing.",
      "Have you tried not dying?"
   ];

   let secondsInScreen = $state(0);

   $effect(() => {
      if (secondsInScreen < RESPAWN_TIME_SECONDS) {
         setTimeout(() => {
            secondsInScreen++;
         }, 1000);
      }
   });

   const tip = randItem(DEATH_TIPS);
</script>

<div id="death-screen">
   <div class="content">
      <h1 class="title">YOU DIED</h1>

      <p class="tip">Tip: {tip}</p>

      <div class="button-container">
      {#if secondsInScreen < RESPAWN_TIME_SECONDS}
         <p class="respawn-countdown">{RESPAWN_TIME_SECONDS - 1 - secondsInScreen}</p>
      {:else}
         <button onclick={sendRespawnPacket}>Respawn</button>
         <button onclick={quitGame}>Quit</button>
      {/if}
      </div>
   </div>

   <div class="bg"></div>
</div>

<style>
   @import url('https://fonts.googleapis.com/css2?family=Inconsolata:wght@400;700;900&display=swap');
   @import url('https://fonts.googleapis.com/css2?family=PT+Serif:wght@700&display=swap');

   #death-screen {
      position: absolute;
      top: 0;
      right: 0;
      bottom: 0;
      left: 0;
      z-index: 2;
   }

   #death-screen .bg {
      background-color: rgba(0, 0, 0, 0.5);
      position: absolute;
      top: 0;
      right: 0;
      bottom: 0;
      left: 0;
      z-index: 1;
      backdrop-filter: blur(2px);
   }

   #death-screen .content {
      width: 75%;
      position: absolute;
      left: 50%;
      top: 50%;
      transform: translate(-50%, -50%);
      z-index: 2;
   }

   #death-screen .content .title {
      color: rgb(255, 0, 0);
      text-align: center;
      text-shadow: 3px 3px 0 #000;
      font-family: "PT Serif";
      font-size: 3rem;
      font-weight: 700;
      margin: 0;
   }

   #death-screen .content .tip {
      color: #ddd;
      font-family: "Calibri";
      font-size: 1.2rem;
      text-align: center;
      text-shadow: 2px 2px 0 #000;
      margin: 0.5rem 0;
   }

   #death-screen .button-container {
      display: inline-block;
      margin-top: 3rem;
      margin-left: 50%;
      transform: translateX(-50%);
   }
   #death-screen .button-container * {
      margin: 0.5rem;
   }
   #death-screen .button-container button {
      font-family: "PT Serif";
      font-size: 1rem;
      background-color: #999;
      border: 3px solid #000;
      padding: 0.2rem 0.6rem;
      cursor: pointer;
      box-shadow: 0 0 3px 1px rgba(0, 0, 0, 0.4) inset;
      outline: none;
   }
   #death-screen .button-container button:hover:not(:active) {
      color: #222;
      background-color: #aaa;
      box-shadow: none;
   }

   #death-screen .respawn-countdown {
      font-family: "PT Serif";
      font-weight: bold;
      font-size: 2.5rem;
      color: red;
      text-shadow: 2px 2px 5px 1px rgba(0, 0, 0, 0.4);
   }
</style>
