// client/src/components/game/TechInfocard.tsx
import { TechID, getTechByID } from "webgl-test-shared/dist/techs";
import { useEffect, useState } from "react";
import Game from "../../Game";
import TechTreeProgressBar from "./tech-tree/TechTreeProgressBar";

export let TechInfocard_setSelectedTech: (techID: TechID | null) => void = () => {};

const TechInfocard = () => {
   const [selectedTech, setSelectedTech] = useState<TechID | null>(null);
   const [studyProgress, setStudyProgress] = useState(0);
   // @Incomplete doesn't refresh on study progress increase

   useEffect(() => {
      TechInfocard_setSelectedTech = (techID: TechID | null): void => {
         setSelectedTech(techID);

         if (techID !== null) {
            setStudyProgress(Game.tribe.techTreeUnlockProgress[techID]?.studyProgress || 0);
         }
      }
   }, []);

   if (selectedTech === null) {
      return null;
   }

   const techInfo = getTechByID(selectedTech);

   return <div id="tech-infocard" className="infocard">
      {studyProgress < techInfo.researchStudyRequirements ? <>
         <div className="flex">
            <h2>{techInfo.name}</h2>
            <img src={require("../../images/tech-tree/" + techInfo.iconSrc)} alt="" />
         </div>
         <TechTreeProgressBar techInfo={techInfo} />
      </> : <>
         <div className="flex">
            <h2>Research Complete!</h2>
            <img src={require("../../images/tech-tree/" + techInfo.iconSrc)} alt="" />
         </div>
      </>}
   </div>;
}

export default TechInfocard;

// client/src/ui/game/TechInfocard.svelte
import { Tech } from "webgl-test-shared/src/techs";
import { useEffect, useState } from "react";
import TechTreeProgressBar from "./tech-tree/TechTreeProgressBar";
import { playerTribe } from "../../game/tribes";

const TechInfocard = () => {
   if (selectedTech === null) {
      return null;
   }

   return <div id="tech-infocard" className="infocard">
      {studyProgress < selectedTech.researchStudyRequirements ? <>
         <div className="flex">
            <h2>{selectedTech.name}</h2>
            <img src={require("../../images/tech-tree/" + selectedTech.iconSrc)} alt="" />
         </div>
         <TechTreeProgressBar techInfo={selectedTech} />
      </> : <>
         <div className="flex">
            <h2>Research Complete!</h2>
            <img src={require("../../images/tech-tree/" + selectedTech.iconSrc)} alt="" />
         </div>
      </>}
   </div>;
}

export default TechInfocard;
