// client/src/components/game/infocards/TribesmanTitleInfocard.tsx
import { TRIBESMAN_TITLE_RECORD, TribesmanTitle } from "webgl-test-shared/dist/titles";
import Client from "../../../client/Client";
import { CLIENT_TITLE_INFO_RECORD } from "../../../client-title-info";

interface TribesmanTitleInfocardProps {
   readonly titleOffer: TribesmanTitle;
}

const TribesmanTitleInfocard = (props: TribesmanTitleInfocardProps) => {
   const accept = (): void => {
      Client.respondToTitleOffer(props.titleOffer, true);
   }
   const reject = (): void => {
      Client.respondToTitleOffer(props.titleOffer, false);
   }
   
   const titleInfo = TRIBESMAN_TITLE_RECORD[props.titleOffer];
   const clientTitleInfo = CLIENT_TITLE_INFO_RECORD[props.titleOffer];
   
   return <div className="infocard sub-menu">
      <p className="center">You have received the {titleInfo.name} title! <i style={{color: "#aaa"}}>(Tier {titleInfo.tier})</i></p>

      <div className="bar"></div>

      <ul>
         {clientTitleInfo.effects.map((effectText, i) => (
            <li key={i}>{effectText}</li>
         ))}
      </ul>

      <div className="flex-container center">
         <button onClick={accept}>Accept</button>
         <button onClick={reject}>Reject</button>
      </div>
   </div>;
}

export default TribesmanTitleInfocard;

// client/src/ui/game/infocards/TribesmanTitleInfocard.svelte
<script lang="ts">
   import { TRIBESMAN_TITLE_RECORD } from "webgl-test-shared/src/titles";
   import { CLIENT_TITLE_INFO_RECORD } from "../../../game/client-title-info";
   import { sendRespondToTitleOfferPacket } from "../../../game/networking/packet-sending";
   import { infocardsState } from "../../../ui-state/infocards-state.svelte";

   const titleOffer = infocardsState.titleOffer;
</script>


{#if titleOffer !== null}
   {@const titleInfo = TRIBESMAN_TITLE_RECORD[titleOffer]}
   {@const clientTitleInfo = CLIENT_TITLE_INFO_RECORD[titleOffer]}

   <div class="infocard sub-menu">
      <p class="center">You have received the {titleInfo.name} title! <i style:color="#aaa">(Tier {titleInfo.tier})</i></p>

      <div class="bar"></div>

      <ul>
         {#each clientTitleInfo.effects as effectText}
            <li>{effectText}</li>
         {/each}
      </ul>

      <div class="flex-container center">
         <button onclick={() => sendRespondToTitleOfferPacket(titleOffer, true)}>Accept</button>
         <button onclick={() => sendRespondToTitleOfferPacket(titleOffer, false)}>Reject</button>
      </div>
   </div>
{/if}
