// client/src/ui/game/GameScreen.svelte
<script lang="ts">
   import ChatBox from "./ChatBox.svelte";
   import CraftingMenu from "./menus/crafting-menu/CraftingMenu.svelte";
   import TechTree from "./tech-tree/TechTree.svelte";
   import BuildMenu from "./menus/BuildMenu.svelte";
   import TechInfocard from "./TechInfocard.svelte";
   import InventorySelector from "./inventories/InventorySelector.svelte";
   import HealthInspector from "./HealthInspector.svelte";
   import Infocards from "./infocards/Infocards.svelte";
   import SummonCrosshair from "./SummonCrosshair.svelte";
   import GameInteractableLayer from "./GameInteractableLayer.svelte";
   import TribePlanVisualiser from "./tribe-plan-visualiser/TribePlanVisualiser.svelte";
   import AnimalStaffOptions from "./AnimalStaffOptions.svelte";
   import TamingMenu from "./taming-menu/TamingMenu.svelte";
   import SignInscribeMenu from "./SignInscribeMenu.svelte";
   import TamingRenamePrompt from "./taming-menu/TamingRenamePrompt.svelte";
   import { GameInteractState, gameUIState } from "../../ui-state/game-ui-state.svelte";
   import DeathScreen from "./DeathScreen.svelte";
   import HealthBar from "./HealthBar.svelte";
   import BackpackInventory from "./inventories/BackpackInventory.svelte";
   import NerdVision from "./dev/NerdVision.svelte";
    import { entityInteractionState } from "../../ui-state/entity-interaction-state.svelte";

   $effect(() => {
      // Reset state
      entityInteractionState.reset();
   });
</script>
   
<GameInteractableLayer />

<ChatBox />

{#if !gameUIState.cinematicModeIsEnabled}
   <HealthBar />
   <Infocards />
{/if}

<!-- Note: BackpackInventoryMenu must be exactly before CraftingMenu because of CSS hijinks -->
<BackpackInventory />
<CraftingMenu  />

{#if gameUIState.isDead}
   <DeathScreen />
{/if}

{#if gameUIState.gameInteractState !== GameInteractState.summonEntity}
   <NerdVision />
{:else}
   <div id="summon-prompt">
      <div class="line left"></div>
      <h2>Click to spawn</h2>
      <div class="line right"></div>
   </div>

   <SummonCrosshair />

   <div id="summon-entity-veil" onMouseDown={e => placeEntity(e.nativeEvent)}></div>
{/if}

<TechTree />
<TechInfocard />

<TribePlanVisualiser />

<BuildMenu />

<InventorySelector />

<HealthInspector />

<AnimalStaffOptions />

<TamingMenu />
<TamingRenamePrompt />

<SignInscribeMenu />

<!-- @SQUEAM for pre-stamina-bar shots -->
<!-- <CowStaminaBar /> -->

{#if gameUIState.canAscendLayer}
   <LayerChangeMessage />
{/if}

{#if !gameUIState.isSimulating}
   <h1 class="simulation-pause-label">(Server simulation has been paused manually)</h1>
{/if}

// client/src/components/game/GameScreen.tsx
import { useCallback, useEffect, useState } from "react";
import ChatBox from "./ChatBox";
import NerdVision from "./dev/NerdVision";
import HealthBar from "./HealthBar";
import Hotbar from "./inventories/Hotbar";
import CraftingMenu from "./menus/CraftingMenu";
import HeldItem from "./HeldItem";
import DeathScreen from "./DeathScreen";
import BackpackInventoryMenu from "./inventories/BackpackInventory";
import TechTree from "./tech-tree/TechTree";
import BuildMenu from "./BuildMenu";
import TechInfocard from "./TechInfocard";
import InventorySelector from "./inventories/InventorySelector";
import InspectHealthBar from "./InspectHealthBar";
import Infocards from "./infocards/Infocards";
import { GameInteractState } from "../../Game";
import SummonCrosshair from "./SummonCrosshair";

export let openSettingsMenu: () => void;
export let closeSettingsMenu: () => void;
export let toggleSettingsMenu: () => void;

export let toggleCinematicMode: () => void;

export let gameScreenSetIsDead: (isDead: boolean) => void = () => {};

interface GameScreenProps {
   readonly interactState: GameInteractState;
}

const GameScreen = (props: GameScreenProps) => {
   const [settingsIsOpen, setSettingsIsOpen] = useState(false);
   const [isDead, setIsDead] = useState(false);
   const [cinematicModeIsEnabled, setCinematicModeIsEnabled] = useState(false);

   useEffect(() => {
      openSettingsMenu = (): void => setSettingsIsOpen(true);
      closeSettingsMenu = (): void => setSettingsIsOpen(false);

      gameScreenSetIsDead = setIsDead;
   }, []);

   useEffect(() => {
      if (cinematicModeIsEnabled) {
         toggleCinematicMode = () => {
            setCinematicModeIsEnabled(false);
         }
      } else {
         toggleCinematicMode = () => {
            setCinematicModeIsEnabled(true);
         }
      }
   }, [cinematicModeIsEnabled]);

   toggleSettingsMenu = useCallback(() => {
      settingsIsOpen ? closeSettingsMenu() : openSettingsMenu();
   }, [settingsIsOpen]);
   
   return <>
      <ChatBox />

      {!cinematicModeIsEnabled ? <>
         <HealthBar isDead={isDead} />
         <Hotbar />
         <Infocards />
      </> : undefined}

      {/* Note: BackpackInventoryMenu must be exactly before CraftingMenu because of CSS hijinks */}
      <BackpackInventoryMenu />
      <CraftingMenu />

      <HeldItem />

      {isDead ? (
         <DeathScreen />
      ) : undefined}

      {props.interactState !== GameInteractState.summonEntity ? (
         <NerdVision />
      ) : <>
         <div id="summon-prompt">
            <div className="line left"></div>
            <h2>Click to spawn</h2>
            <div className="line right"></div>
         </div>

         <SummonCrosshair />
      </>}

      <TechTree />
      <TechInfocard />

      <BuildMenu />

      <InventorySelector />

      <InspectHealthBar />
   </>;
}

export default GameScreen;
