// client/src/svelte/game/GameScreen.svelte
<script lang="ts">
   import ChatBox from "./ChatBox";
   import CraftingMenu from "./menus/CraftingMenu";
   import TechTree from "./tech-tree/TechTree";
   import BuildMenu from "./BuildMenu";
   import TechInfocard from "./TechInfocard";
   import InventorySelector from "./inventories/InventorySelector";
   import HealthInspector from "./HealthInspector";
   import Infocards from "./infocards/Infocards";
   import SummonCrosshair from "./SummonCrosshair";
   import GameInteractableLayer from "./GameInteractableLayer";
   import TribePlanVisualiser from "./tribe-plan-visualiser/TribePlanVisualiser";
   import { ItemTooltip } from "./inventories/ItemTooltip";
   import AnimalStaffOptions from "./AnimalStaffOptions";
   import TamingMenu from "./taming-menu/TamingMenu";
   import SignInscribeMenu from "./SignInscribeMenu";
   import TamingRenamePrompt from "./taming-menu/TamingRenamePrompt";
</script>
   
<GameInteractableLayer hotbar={hotbar} offhand={offhand} backpackSlot={backpackSlot} armourSlot={armourSlot} gloveSlot={gloveSlot} heldItemSlot={heldItemSlot} cinematicModeIsEnabled={cinematicModeIsEnabled} gameInteractState={interactState} setGameInteractState={setInteractState} />

<ChatBox />

{!cinematicModeIsEnabled ? <>
   <HealthBar isDead={isDead} />
   <Infocards />
</> : undefined}

{/* Note: BackpackInventoryMenu must be exactly before CraftingMenu because of CSS hijinks */}
<BackpackInventoryMenu />
<CraftingMenu craftingOutputSlot={craftingOutputSlot} hotbar={hotbar} backpack={backpack} />

{isDead ? (
   <DeathScreen setAppState={props.setAppState} />
) : undefined}

{interactState !== GameInteractState.summonEntity ? (
   <NerdVision isSimulating={isSimulating} summonPacketRef={summonPacketRef} setGameInteractState={setInteractState} />
) : <>
   <div id="summon-prompt">
      <div className="line left"></div>
      <h2>Click to spawn</h2>
      <div className="line right"></div>
   </div>

   <SummonCrosshair />

   <div id="summon-entity-veil" onMouseDown={e => placeEntity(e.nativeEvent)}></div>
</>}

<TechTree />
<TechInfocard />

<TribePlanVisualiser />

<BuildMenu />

<InventorySelector />

<HealthInspector />

<ItemTooltip />

<AnimalStaffOptions setGameInteractState={setInteractState} />

<TamingMenu />
<TamingRenamePrompt />

<SignInscribeMenu />

{/* @SQUEAM for pre-stamina-bar shots */}
{/* <CowStaminaBar /> */}

{ canAscendLayer ? (
   <LayerChangeMessage />
) : null }

{ !isSimulating ? (
   <h1 className="simulation-pause-label">(Server simulation has been paused manually)</h1>
) : undefined}

// client/src/components/game/GameScreen.tsx
import { useCallback, useEffect, useState } from "react";
import ChatBox from "./ChatBox";
import NerdVision from "./dev/NerdVision";
import HealthBar from "./HealthBar";
import Hotbar from "./inventories/Hotbar";
import CraftingMenu from "./menus/CraftingMenu";
import HeldItem from "./HeldItem";
import DeathScreen from "./DeathScreen";
import BackpackInventoryMenu from "./inventories/BackpackInventory";
import TechTree from "./tech-tree/TechTree";
import BuildMenu from "./BuildMenu";
import TechInfocard from "./TechInfocard";
import InventorySelector from "./inventories/InventorySelector";
import InspectHealthBar from "./InspectHealthBar";
import Infocards from "./infocards/Infocards";
import { GameInteractState } from "../../Game";
import SummonCrosshair from "./SummonCrosshair";

export let openSettingsMenu: () => void;
export let closeSettingsMenu: () => void;
export let toggleSettingsMenu: () => void;

export let toggleCinematicMode: () => void;

export let gameScreenSetIsDead: (isDead: boolean) => void = () => {};

interface GameScreenProps {
   readonly interactState: GameInteractState;
}

const GameScreen = (props: GameScreenProps) => {
   const [settingsIsOpen, setSettingsIsOpen] = useState(false);
   const [isDead, setIsDead] = useState(false);
   const [cinematicModeIsEnabled, setCinematicModeIsEnabled] = useState(false);

   useEffect(() => {
      openSettingsMenu = (): void => setSettingsIsOpen(true);
      closeSettingsMenu = (): void => setSettingsIsOpen(false);

      gameScreenSetIsDead = setIsDead;
   }, []);

   useEffect(() => {
      if (cinematicModeIsEnabled) {
         toggleCinematicMode = () => {
            setCinematicModeIsEnabled(false);
         }
      } else {
         toggleCinematicMode = () => {
            setCinematicModeIsEnabled(true);
         }
      }
   }, [cinematicModeIsEnabled]);

   toggleSettingsMenu = useCallback(() => {
      settingsIsOpen ? closeSettingsMenu() : openSettingsMenu();
   }, [settingsIsOpen]);
   
   return <>
      <ChatBox />

      {!cinematicModeIsEnabled ? <>
         <HealthBar isDead={isDead} />
         <Hotbar />
         <Infocards />
      </> : undefined}

      {/* Note: BackpackInventoryMenu must be exactly before CraftingMenu because of CSS hijinks */}
      <BackpackInventoryMenu />
      <CraftingMenu />

      <HeldItem />

      {isDead ? (
         <DeathScreen />
      ) : undefined}

      {props.interactState !== GameInteractState.summonEntity ? (
         <NerdVision />
      ) : <>
         <div id="summon-prompt">
            <div className="line left"></div>
            <h2>Click to spawn</h2>
            <div className="line right"></div>
         </div>

         <SummonCrosshair />
      </>}

      <TechTree />
      <TechInfocard />

      <BuildMenu />

      <InventorySelector />

      <InspectHealthBar />
   </>;
}

export default GameScreen;
