// client/src/components/App.tsx
import { TribeType } from "battletribes-shared/tribes";
import { useRef, useState } from "react";
import GameScreen from "./game/GameScreen";
import LoadingScreen from "./LoadingScreen";
import FrameGraph from "./game/dev/FrameGraph";
import MainMenu from "./MainMenu";

export const enum AppState {
   mainMenu,
   loading,
   game
}

function App() {
   const usernameRef = useRef("");
   const tribeTypeRef = useRef(TribeType.plainspeople);
   const [appState, setAppState] = useState(AppState.mainMenu);

   return <>
      {appState === AppState.mainMenu ? <>
         <MainMenu existingUsername={usernameRef.current} usernameRef={usernameRef} tribeTypeRef={tribeTypeRef} setAppState={setAppState} />
      </> : appState === AppState.loading ? <>
         <LoadingScreen username={usernameRef.current} tribeType={tribeTypeRef.current} setAppState={setAppState} />
      </> : appState === AppState.game ? <>
         <GameScreen setAppState={setAppState} />
      </> : null}

      <div id="canvas-wrapper" className={appState !== AppState.game ? "hidden" : undefined}>
         <canvas id="game-canvas"></canvas>
         <canvas id="text-canvas"></canvas>
         <canvas id="tech-tree-canvas" className="hidden"></canvas>
         <FrameGraph />
      </div>
   </>;
}

export default App;

// client/src/svelte/App.svelte
<script lang="ts">
   import { onKeyDown, onKeyUp } from "../game/keyboard-input";
   import { AppState, appState } from "../stores/app-state.svelte";
   import FrameGraph from "./game/dev/FrameGraph.svelte";
   import GameScreen from "./game/GameScreen.svelte";
   import LoadingScreen from "./LoadingScreen.svelte";
   import MainMenu from "./MainMenu.svelte";
   import { createPlayerInputListeners } from "./game/GameInteractableLayer";
</script>

<svelte:window
   on:load={createPlayerInputListeners}
   on:keydown={onKeyDown}
   on:keyup={onKeyUp}
/>

{#if appState === AppState.mainMenu}
   <MainMenu />
{:else if appState === AppState.loading}
   <LoadingScreen />
{:else if appState === AppState.game}
   <GameScreen />
{/if}

<div id="canvas-wrapper" class={appState !== AppState.game ? "hidden" : undefined}>
   <canvas id="game-canvas"></canvas>
   <canvas id="text-canvas"></canvas>
   <canvas id="tech-tree-canvas" class="hidden"></canvas>
   <canvas id="tribe-plan-visualiser-canvas" class="hidden"></canvas>
   <FrameGraph />
</div>

<style>
   #text-canvas {
      pointer-events: none;
   }
</style>
