// client/src/ui/game/inventories/BarrelInventory.svelte
<script lang="ts">
   import { InventoryName } from "webgl-test-shared/src/items/items";
   import { getInventory, InventoryComponentArray } from "../../../game/entity-components/server-components/InventoryComponent";
   import { assert } from "../../../../../shared/src/utils";
   import MenuElem from "../menus/MenuElem.svelte";
   import InventoryContainer from "./InventoryContainer.svelte";
   import { entityInteractionState } from "../../../ui-state/entity-interaction-state.svelte";

   // @Hack: "!"
   const barrel = entityInteractionState.selectedEntity!;
   const inventoryComponent = InventoryComponentArray.getComponent(barrel)!;

   const inventory = getInventory(inventoryComponent, InventoryName.inventory);
   assert(inventory !== null);
</script>

<MenuElem id="barrel-inventory" class="menu">
   <h2 class="menu-title">Barrel</h2>
   <div class="area">
      <label>
         <input type="checkbox" defaultChecked={true} />
         Allow friendly tribesmen
      </label>
      <label>
         <input type="checkbox" defaultChecked={false} />
         Allow enemies
      </label>
   </div>
   <div class="flex-container center">
      <InventoryContainer entityID={barrel} inventory={inventory} />
   </div>
</MenuElem>

// client/src/svelte/game/inventories/BarrelInventory.tsx
import InventoryContainer from "./InventoryContainer";
import { getSelectedEntity } from "../../../game/entity-selection";
import { InventoryName } from "battletribes-shared/items/items";
import { getInventory, InventoryComponentArray } from "../../../game/entity-components/server-components/InventoryComponent";
import Menu from "../menus/Menu";
import { assert } from "../../../../../shared/src/utils";

const BarrelInventory = () => {
   const barrel = getSelectedEntity();
   const inventoryComponent = InventoryComponentArray.getComponent(barrel);

   const inventory = getInventory(inventoryComponent, InventoryName.inventory);
   assert(inventory !== null);
   
   return <>
      <Menu id="barrel-inventory" className="menu">
         <h2 className="menu-title">Barrel</h2>
         <div className="area">
            <label>
               <input type="checkbox" defaultChecked={true} />
               Allow friendly tribesmen
            </label>
            <label>
               <input type="checkbox" defaultChecked={false} />
               Allow enemies
            </label>
         </div>
         <div className="flex-container center">
            <InventoryContainer entityID={barrel} inventory={inventory} />
         </div>
      </Menu>
   </>;
}

export default BarrelInventory;
