// client/src/components/game/dev/DevmodeScrollableOptions.tsx
import { useState } from "react";

interface OptionProps {
   readonly text: string;
   readonly isSelected: boolean;
   onClick(): void;
}

interface DevmodeScrollableOptionsProps {
   readonly options: ReadonlyArray<string>;
   onOptionSelect(optionIdx: number): void;
}

const Option = (props: OptionProps) => {
   let className = "option";
   if (props.isSelected) {
      className += " selected";
   }
   
   return <li className={className} onClick={props.onClick}>
      <span className="text">{props.text}</span>
      {props.isSelected ? (
         <div className="selection-marker"></div>
      ) : null}
   </li>;
}

const DevmodeScrollableOptions = (props: DevmodeScrollableOptionsProps) => {
   const [selectedOptionIdx, setSelectedOptionIdx] = useState(0);
   
   const elems = new Array<JSX.Element>();
   for (let i = 0; i < props.options.length; i++) {
      if (i > 0) {
         const isBright = i === selectedOptionIdx || i === selectedOptionIdx + 1;
         elems.push(
            <div key={elems.length} className={`separator${isBright ? " bright" : ""}`}></div>
         );
      }

      const text = props.options[i];
      elems.push(
         <Option key={elems.length} text={text} isSelected={i === selectedOptionIdx} onClick={() => { setSelectedOptionIdx(i); props.onOptionSelect(i) }} />
      );
   }

   return <div className="devmode-scrollable-options devmode-menu-section flex-container">
      <ul>
         {elems}
      </ul>
   </div>;
}

export default DevmodeScrollableOptions;

// client/src/ui/game/dev/DevmodeScrollableOptions.svelte
<script lang="ts">
   import DevmodeScrollableOption from "./DevmodeScrollableOption.svelte";

   interface Props {
      readonly options: ReadonlyArray<string>;
      onOptionSelect(optionIdx: number): void;
   }

   let props: Props = $props();

   let selectedOptionIdx = $state(0);
   
</script>

<div class="devmode-scrollable-options devmode-menu-section flex-container">
   <ul>
      {#each props.options as _, i}
         {#if i > 0}
            {@const isBright = i === selectedOptionIdx || i === selectedOptionIdx + 1}
            <div class="separator" class:bright={isBright}></div>
         {/if}

         {@const text = props.options[i]}
         <DevmodeScrollableOption text={text} isSelected={i === selectedOptionIdx} onClick={() => { selectedOptionIdx = i; props.onOptionSelect(i) }} />
      {/each}
   </ul>
</div>
